### ISSUE TITLE
Text input box sometimes becomes unselectable after Alt+Tabbing away

### ISSUE THREAD

**Issue by mistymntncop** [EpicGames/raddebugger#116]
Steps to reproduce:
1. Open up "Go To Address" Alt+G
2. Input some text e.g. "hello world"
3. Alt+Tab away from RADDBG and then Alt+Tab back into RADDBG

Sometimes (maybe like every second time) you tab back the input box text becomes unselectable/the caret doesn't show up. Doesn't become clickable again until you press the Escape key.

It looks like this:
![image](https://github.com/EpicGames/raddebugger/assets/105329747/fe4303a4-02ed-4425-b6af-7f18c4867eb1)

**Comment by ryanfleury** [comment]
This is probably due to the menu bar being focused. I’ll write a fix to make this behavior more consistent with other Windows programs, but this should be fixed if you just press Alt again.

**Comment by ryanfleury** [comment]
This actually seems to have been fixed by my changes yesterday to properly handle AltGr, which makes the debugger slightly more restrictive w.r.t. Alt hotkeys in their activation of the menu bar. Let me know if you still run into issues with this.

**Comment by mistymntncop** [comment]
hmm, I built dev and am still experiencing the bug :(. Like you said the menu bar is the focused not the textbox. Sometimes it is selectable but perhaps thats from the Alt when I Alt+Tab back to RADDBG.
