### ISSUE TITLE
Static and global variables are not evaluated without namespace

### ISSUE THREAD

**Issue by MohitSethi99** [EpicGames/raddebugger#55]
- Static and global variables are not evaluated without namespace even though the cursor is in the same namespace. (issue persists with mouse hover)
- Class static variables are not evaluated on mouse hover.

![image](https://github.com/EpicGames/raddebugger/assets/29519295/d9b5c0ee-6fee-487d-9a90-f89c8d068df8)
![image](https://github.com/EpicGames/raddebugger/assets/29519295/68f8276a-b9bf-4e98-9d46-d40affb40414)

**Comment by ryanfleury** [comment]
Fixed as of f48d8431c0b0940136a9756a34cf1fdb833bbf40.

**Comment by MohitSethi99** [comment]
Mouse hover still shows wrong value
![image](https://github.com/EpicGames/raddebugger/assets/29519295/8cd309a0-91b3-42d5-b324-bde6836db8d2)

**Comment by MohitSethi99** [comment]
Another note (maybe helpful): clicking `Alt+W` while cursor on Line `24` adds `b` to watch window instead of `Test::b`.

**Comment by ryanfleury** [comment]
Can you try this again on the latest commits? I've fixed some things w.r.t. global evaluation, and want to see if this is another manifestation of those bugs.

**Comment by MohitSethi99** [comment]
Built 96b0dd078330cb0e17f9ef66eab6228b58e1da58
Seems to be broken again, nothing on hover over the static and global variables.
<img width="760" alt="Screenshot 2024-01-25 105007" src="https://github.com/EpicGames/raddebugger/assets/29519295/98a74e85-bf2d-4525-8183-786f793f202f">

**Comment by ryanfleury** [comment]
This is not the same test as original, as you're inside of `NS::Log::Trace` rather than `NS::Func`, so it isn't really testing what I was hoping to fix. But it did raise that other issue (e.g. nested namespaces), so I'll go ahead and fix that as well.

**Comment by MohitSethi99** [comment]
Oh okay, I tested with original code. Everything in watch seems to work perfectly for this case.
Hover on Test::b doesn't show the value and Alt+W over that line adds `b` to the watch window.
<img width="900" alt="image" src="https://github.com/EpicGames/raddebugger/assets/29519295/c5165cd7-959a-4aa6-855c-0c622f64622b">

**Comment by ryanfleury** [comment]
Great. As of 66b56789c6898049b994fdc7af5b2f99d53915ac, nested namespaces should now work, with the eval system's parser prioritizing more deeply nested namespace prefixes, then falling back on shallower ones. So inside of `Foo::Bar::Baz`, if `X` does not resolve to anything local, it will try to resolve as `Foo::Bar::X` first, then `Foo::X`.

As of ed7d31d7eafb4892e92c0ffc3e6b3a2f53f38ed0, hover evaluation & Alt+W will account for scope resolution operators in its "expression range forming" path, so that should fix that separate issue.

**Comment by MohitSethi99** [comment]
Everything works perfectly, thanks for the fixes!
